apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: default
  labels: { app: portfolio }
  annotations: { keel.sh/policy: force }
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector: { matchLabels: { app: portfolio } }
  template:
    metadata: { labels: { app: portfolio } }
    spec:
      containers:
        - name: portfolio
          image: ghcr.io/mp281x/portfolio:latest
          ports: [containerPort: 3000]

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: default
spec:
  selector: { app: portfolio }
  ports: [{ port: 3000, name: portfolio, targetPort: 3000 }]

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`portfolio.mp281x.xyz`)
      kind: Rule
      services: [{ name: portfolio, port: 3000 }]
