/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homeSkillsRouteImport } from './routes/(home)/skills'
import { Route as homeProjectsRouteImport } from './routes/(home)/projects'
import { Route as homeCvRouteImport } from './routes/(home)/cv'
import { Route as homeAboutRouteImport } from './routes/(home)/about'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeSkillsRoute = homeSkillsRouteImport.update({
  id: '/(home)/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const homeProjectsRoute = homeProjectsRouteImport.update({
  id: '/(home)/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const homeCvRoute = homeCvRouteImport.update({
  id: '/(home)/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const homeAboutRoute = homeAboutRouteImport.update({
  id: '/(home)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof homeAboutRoute
  '/cv': typeof homeCvRoute
  '/projects': typeof homeProjectsRoute
  '/skills': typeof homeSkillsRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof homeAboutRoute
  '/cv': typeof homeCvRoute
  '/projects': typeof homeProjectsRoute
  '/skills': typeof homeSkillsRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/about': typeof homeAboutRoute
  '/(home)/cv': typeof homeCvRoute
  '/(home)/projects': typeof homeProjectsRoute
  '/(home)/skills': typeof homeSkillsRoute
  '/(home)/': typeof homeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/cv' | '/projects' | '/skills' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/cv' | '/projects' | '/skills' | '/'
  id:
    | '__root__'
    | '/(home)/about'
    | '/(home)/cv'
    | '/(home)/projects'
    | '/(home)/skills'
    | '/(home)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeAboutRoute: typeof homeAboutRoute
  homeCvRoute: typeof homeCvRoute
  homeProjectsRoute: typeof homeProjectsRoute
  homeSkillsRoute: typeof homeSkillsRoute
  homeIndexRoute: typeof homeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/skills': {
      id: '/(home)/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof homeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/projects': {
      id: '/(home)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof homeProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/cv': {
      id: '/(home)/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof homeCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/about': {
      id: '/(home)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeAboutRoute: homeAboutRoute,
  homeCvRoute: homeCvRoute,
  homeProjectsRoute: homeProjectsRoute,
  homeSkillsRoute: homeSkillsRoute,
  homeIndexRoute: homeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
