name: Build portfolio

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl delete pod -l app=portfolio --namespace kaniko
